version: '3.4'

services:
  postgres:
    image: postgres:latest
    container_name: "postgres-quarkus-test"
    network_mode: host
    ports:
      - "5432:5432"    
    environment:
      - POSTGRES_PASSWORD=quarkus_test
      - POSTGRES_USER=quarkus_test
      - POSTGRES_DB=quarkus_test_db
  quarkus:
    image: temenos/com.temenos.security.random-generator:1.0.0-SNAPSHOT
    container_name: "random-generator"
    network_mode: host
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - quarkus.datasource.user.jdbc.url=jdbc:postgresql://127.0.0.1:5432/quarkus_test
      - quarkus.datasource.user.username=quarkus_test
      - quarkus.datasource.user.password=quarkus_test
    